### ISSUE TITLE
Mojibake in license 

### ISSUE THREAD

**Issue by pombredanne** [OpenTermsArchive/GenAI-versions#3]
See https://github.com/OpenTermsArchive/GenAI-versions/blob/79a12775902409b43e2297bd4bdbada4253d10fb/LICENSE#L46

**Comment by clementbiron** [comment]
Thank you very much for pointing out this anomaly 🙏 

I've just suggested a correction in #6.

**Comment by MattiSG** [comment]
Thanks, this had cascaded throughout the ecosystem through our Demo template collection, which we fixed thanks to your report in https://github.com/OpenTermsArchive/demo-versions/pull/5 😃
